package org.angryscan.common.extensions

import org.angryscan.common.engine.IMatcher
import org.angryscan.common.matchers.*

object Matchers: List<IMatcher> by listOf<IMatcher>(
    Address,
    AddressUS,
    APOFPODPO,
    AlienRegistrationNumber,
    BankAccount,
    BankAccountLE,
    Birthday,
    CadastralNumber,
    Certificate,
    CardNumber(),
    CryptoSeedPhrase,
    CryptoWallet,
    CVV,
    DeathDate,
    DODID,
    DriverLicense,
    DriverLicenseUS,
    EducationDoc,
    EducationLevel,
    EducationLicense,
    Email,
    EIN,
    ExecDocNumber,
    RIN,
    RTN,
    FullName,
    FullNameUS,
    Geo,
    HashData,
    IdentityDocType,
    INN,
    ITIN,
    IPv4,
    IPv6,
    LegalEntityId,
    LegalEntityName,
    Login,
    MaritalStatus,
    MedicareUS,
    MilitaryID,
    MilitaryRank,
    NPI,
    NSN,
    OGRNIP,
    USCIS,
    OKPO,
    OMS,
    OSAGOPolicy,
    Passport,
    PassportUS,
    Password,
    Phone,
    PhoneUS,
    ResidencePermit,
    SberBook,
    SecurityAffiliation,
    SNILS,
    SocialUserId,
    SEVISID,
    TCN,
    SSN,
    StateRegContract,
    VIN,
    VehicleRegNumber,
    VisaNumberUS,
) {
    override fun contains(element: IMatcher): Boolean {
        return this.any{
            it::class == element::class
        }
    }
}